# Mintree Shell Integration for Zsh
# ==================================
#
# Generated by `mintree helpers shell-init zsh`. Eval this in your ~/.zshrc:
#   eval "$(mintree helpers shell-init zsh)"
#
# What it does:
#  1. Wraps the `mintree` binary so the parent shell can `cd` into a freshly
#     created worktree. The binary itself can't change the parent's cwd, so
#     it emits `MINTREE_CD:<path>` markers on stdout that this wrapper picks
#     up and translates into a real `cd`.
#  2. When `worktree create --work` is used, also reads `MINTREE_WORK:1`,
#     `MINTREE_WORK_PROMPT_FILE:<path>`, and `MINTREE_PERMISSION_MODE:<mode>`
#     and chains a `mintree worktree work` invocation right after the cd.
#  3. Recovers the current shell when its cwd was deleted (e.g. after
#     `mintree worktree remove`) — falls back to the main repo, then to $HOME.
#  4. Exposes the `mt` / `mtw` / `mtn` aliases (`mtn` prompts for a branch).
#  5. Exports MINTREE_SHELL_INTEGRATION=1 so `mintree doctor` can verify the
#     wrapper is loaded.

export MINTREE_SHELL_INTEGRATION=1

function mintree() {
    # Recover from a deleted cwd. If the current directory was a mintree
    # worktree that was just removed, return to the main repo; otherwise
    # bounce to $HOME so subsequent commands don't error out cryptically.
    if [[ ! -d "$(pwd 2>/dev/null)" ]]; then
        local current_path="$(pwd 2>/dev/null)"
        if [[ "$current_path" == */.mintree/worktrees/* ]]; then
            local main_repo="${current_path%%/.mintree/worktrees/*}"
            if [[ -d "$main_repo" ]]; then
                echo "⚠ Worktree directory deleted. Returning to main repo."
                cd "$main_repo" || cd ~ || return 1
            else
                cd ~ || return 1
            fi
        else
            echo "⚠ Current directory no longer exists. Returning to home."
            cd ~ || return 1
        fi
    fi

    # Walks a marker block (whatever `worktree create` emitted, captured into
    # $1 with no ANSI) and turns the markers into shell side-effects: cd to
    # the new worktree, then optionally chain `worktree work` with the right
    # flags. Returns 0 when the cd succeeded, 1 when there was nothing to do.
    _mintree_handle_markers() {
        local clean_output="$1"
        local target_dir
        target_dir=$(echo "$clean_output" | grep "MINTREE_CD:" | sed 's/.*MINTREE_CD://')
        if [[ -z "$target_dir" || ! -d "$target_dir" ]]; then
            return 1
        fi
        cd "$target_dir" && echo "Switched to: $target_dir"

        local perm_mode
        perm_mode=$(echo "$clean_output" | grep "MINTREE_PERMISSION_MODE:" | sed 's/.*MINTREE_PERMISSION_MODE://')

        # Orchestrate: launch a Claude orchestrator in the repo root (already
        # cd'd above) with the batch prompt. Takes precedence over WORK — the
        # two markers are never emitted together.
        if [[ "$clean_output" == *MINTREE_ORCHESTRATE:* ]]; then
            local extra=()
            local orch_prompt_file
            orch_prompt_file=$(echo "$clean_output" | grep "MINTREE_ORCHESTRATE_PROMPT_FILE:" | sed 's/.*MINTREE_ORCHESTRATE_PROMPT_FILE://')
            [[ -n "$orch_prompt_file" ]] && extra+=(--prompt-file "$orch_prompt_file")
            [[ -n "$perm_mode" ]] && extra+=(--permission-mode "$perm_mode")
            local orch_rc_name
            orch_rc_name=$(echo "$clean_output" | grep "MINTREE_ORCHESTRATE_RC_NAME:" | sed 's/.*MINTREE_ORCHESTRATE_RC_NAME://')
            [[ -n "$orch_rc_name" ]] && extra+=(--rc-name "$orch_rc_name")
            command mintree orchestrate "${extra[@]}"
            return $?
        fi

        if [[ "$clean_output" != *MINTREE_WORK:* ]]; then
            return 0
        fi
        local extra=()
        local prompt_file
        prompt_file=$(echo "$clean_output" | grep "MINTREE_WORK_PROMPT_FILE:" | sed 's/.*MINTREE_WORK_PROMPT_FILE://')
        [[ -n "$prompt_file" ]] && extra+=(--prompt-file "$prompt_file")
        [[ -n "$perm_mode" ]] && extra+=(--permission-mode "$perm_mode")
        command mintree worktree work "${extra[@]}"
        return $?
    }

    # `worktree create`: capture stdout so we can grep for markers, print the
    # rest to the user, then run the side-effects.
    if [[ "$1" == "worktree" && "$2" == "create" ]]; then
        local output
        output=$(command mintree "$@" 2>&1)
        local exit_code=$?

        if [[ "$output" == *MINTREE_CD:* ]]; then
            echo "$output" | grep -vE "MINTREE_(CD|WORK|WORK_PROMPT_FILE|PERMISSION_MODE|ORCHESTRATE|ORCHESTRATE_PROMPT_FILE):"
            local clean_output=$(echo "$output" | sed 's/\x1b\[[0-9;]*m//g')
            _mintree_handle_markers "$clean_output"
        else
            echo "$output"
        fi
        return $exit_code
    fi

    # `dashboard`: the TUI owns the TTY, so we can't capture stdout without
    # breaking rendering. Instead, hand the binary a temp file via env var
    # and let it write markers there directly. Once the dashboard exits we
    # read whatever's in the file and run the same side-effects as create.
    if [[ "$1" == "dashboard" ]]; then
        local marker_file
        marker_file=$(mktemp -t mintree-markers)
        MINTREE_MARKER_FILE="$marker_file" command mintree "$@"
        local exit_code=$?
        if [[ -s "$marker_file" ]]; then
            local clean_output=$(cat "$marker_file" | sed 's/\x1b\[[0-9;]*m//g')
            _mintree_handle_markers "$clean_output"
        fi
        rm -f "$marker_file"
        return $exit_code
    fi

    command mintree "$@"
}

# Aliases as functions so they survive `eval` (zsh expands aliases at
# parse time, which is too early when the eval and the call live on the
# same script line). Functions are looked up at call time and always work.
function mt() {
    mintree "$@"
}

function mtw() {
    mintree worktree "$@"
}

# `mtn` — interactive shortcut: prompt for a branch then create the worktree
# and start working on it. Equivalent to santree's `stn`.
function mtn() {
    local branch
    vared -p "Branch name: " branch
    [[ -z "$branch" ]] && echo "Branch name required" && return 1
    mintree worktree create "$branch" --work
}
