# Mintree Shell Integration for Bash
# ===================================
#
# Generated by `mintree helpers shell-init bash`. Eval this in your ~/.bashrc:
#   eval "$(mintree helpers shell-init bash)"
#
# What it does:
#  1. Wraps the `mintree` binary so the parent shell can `cd` into a freshly
#     created worktree. The binary itself can't change the parent's cwd, so
#     it emits `MINTREE_CD:<path>` markers on stdout that this wrapper picks
#     up and translates into a real `cd`.
#  2. Recovers the current shell when its cwd was deleted (e.g. after
#     `mintree worktree remove`) — falls back to the main repo, then to $HOME.
#  3. Exposes the `mt` / `mtw` / `mtn` aliases (`mtn` prompts for a branch).
#  4. Exports MINTREE_SHELL_INTEGRATION=1 so `mintree doctor` can verify the
#     wrapper is loaded.

export MINTREE_SHELL_INTEGRATION=1

function mintree() {
    if [[ ! -d "$(pwd 2>/dev/null)" ]]; then
        local current_path="$(pwd 2>/dev/null)"
        if [[ "$current_path" == */.mintree/worktrees/* ]]; then
            local main_repo="${current_path%%/.mintree/worktrees/*}"
            if [[ -d "$main_repo" ]]; then
                echo "⚠ Worktree directory deleted. Returning to main repo."
                cd "$main_repo" || cd ~ || return 1
            else
                cd ~ || return 1
            fi
        else
            echo "⚠ Current directory no longer exists. Returning to home."
            cd ~ || return 1
        fi
    fi

    _mintree_handle_markers() {
        local clean_output="$1"
        local target_dir
        target_dir=$(echo "$clean_output" | grep "MINTREE_CD:" | sed 's/.*MINTREE_CD://')
        if [[ -z "$target_dir" || ! -d "$target_dir" ]]; then
            return 1
        fi
        cd "$target_dir" && echo "Switched to: $target_dir"

        local perm_mode
        perm_mode=$(echo "$clean_output" | grep "MINTREE_PERMISSION_MODE:" | sed 's/.*MINTREE_PERMISSION_MODE://')

        # Orchestrate: launch a Claude orchestrator in the repo root (already
        # cd'd above) with the batch prompt. Takes precedence over WORK — the
        # two markers are never emitted together.
        if [[ "$clean_output" == *MINTREE_ORCHESTRATE:* ]]; then
            local extra=()
            local orch_prompt_file
            orch_prompt_file=$(echo "$clean_output" | grep "MINTREE_ORCHESTRATE_PROMPT_FILE:" | sed 's/.*MINTREE_ORCHESTRATE_PROMPT_FILE://')
            [[ -n "$orch_prompt_file" ]] && extra+=(--prompt-file "$orch_prompt_file")
            [[ -n "$perm_mode" ]] && extra+=(--permission-mode "$perm_mode")
            local orch_rc_name
            orch_rc_name=$(echo "$clean_output" | grep "MINTREE_ORCHESTRATE_RC_NAME:" | sed 's/.*MINTREE_ORCHESTRATE_RC_NAME://')
            [[ -n "$orch_rc_name" ]] && extra+=(--rc-name "$orch_rc_name")
            command mintree orchestrate "${extra[@]}"
            return $?
        fi

        if [[ "$clean_output" != *MINTREE_WORK:* ]]; then
            return 0
        fi
        local extra=()
        local prompt_file
        prompt_file=$(echo "$clean_output" | grep "MINTREE_WORK_PROMPT_FILE:" | sed 's/.*MINTREE_WORK_PROMPT_FILE://')
        [[ -n "$prompt_file" ]] && extra+=(--prompt-file "$prompt_file")
        [[ -n "$perm_mode" ]] && extra+=(--permission-mode "$perm_mode")
        command mintree worktree work "${extra[@]}"
        return $?
    }

    if [[ "$1" == "worktree" && "$2" == "create" ]]; then
        local output
        output=$(command mintree "$@" 2>&1)
        local exit_code=$?

        if [[ "$output" == *MINTREE_CD:* ]]; then
            echo "$output" | grep -vE "MINTREE_(CD|WORK|WORK_PROMPT_FILE|PERMISSION_MODE|ORCHESTRATE|ORCHESTRATE_PROMPT_FILE):"
            local clean_output=$(echo "$output" | sed 's/\x1b\[[0-9;]*m//g')
            _mintree_handle_markers "$clean_output"
        else
            echo "$output"
        fi
        return $exit_code
    fi

    if [[ "$1" == "dashboard" ]]; then
        local marker_file
        marker_file=$(mktemp -t mintree-markers)
        MINTREE_MARKER_FILE="$marker_file" command mintree "$@"
        local exit_code=$?
        if [[ -s "$marker_file" ]]; then
            local clean_output=$(cat "$marker_file" | sed 's/\x1b\[[0-9;]*m//g')
            _mintree_handle_markers "$clean_output"
        fi
        rm -f "$marker_file"
        return $exit_code
    fi

    command mintree "$@"
}

# Aliases as functions so they work in non-interactive shells too (bash
# expands aliases only in interactive mode; functions always work).
function mt() {
    mintree "$@"
}

function mtw() {
    mintree worktree "$@"
}

function mtn() {
    local branch
    read -p "Branch name: " branch
    [[ -z "$branch" ]] && echo "Branch name required" && return 1
    mintree worktree create "$branch" --work
}
